/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.bonusfuncionario.View;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author tarci
 */
public class ManterFuncionarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManterFuncionario
     */
    public ManterFuncionarioView() {
        initComponents();
        setVisible(true);
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JCheckBox getCheckBoxFuncionarioDoMes() {
        return checkBoxFuncionarioDoMes;
    }

    public JComboBox<String> getComboBoxBonus() {
        return comboBoxBonus;
    }

    public JComboBox<String> getComboBoxCargo() {
        return comboBoxCargo;
    }

    public JFormattedTextField getTxtFormatedFieldAdmissao() {
        return txtFormatedFieldAdmissao;
    }

    public JTextField getTxtFieldFaltas() {
        return txtFieldFaltas;
    }

    public JTextField getTxtFieldIdade() {
        return txtFieldIdade;
    }

    public JTextField getTxtFieldNome() {
        return txtFieldNome;
    }

    public JTextField getTxtFieldSalario() {
        return txtFieldSalario;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCargo = new javax.swing.JLabel();
        comboBoxCargo = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        txtFieldNome = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        txtFieldIdade = new javax.swing.JTextField();
        lblBonus = new javax.swing.JLabel();
        comboBoxBonus = new javax.swing.JComboBox<>();
        lblSalario = new javax.swing.JLabel();
        txtFieldSalario = new javax.swing.JTextField();
        lblFaltas = new javax.swing.JLabel();
        txtFieldFaltas = new javax.swing.JTextField();
        checkBoxFuncionarioDoMes = new javax.swing.JCheckBox();
        lblAdmissao = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtFormatedFieldAdmissao = new javax.swing.JFormattedTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);

        lblCargo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblCargo.setText("Cargo");

        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Analista de TI", "Supervisor", "Programador", "Trainee", "Assistente" }));
        comboBoxCargo.setSelectedIndex(5);

        lblNome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        txtFieldNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblIdade.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblIdade.setText("Idade");

        txtFieldIdade.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblBonus.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblBonus.setText("Bônus");

        comboBoxBonus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bonus Normal", "Bonus Generoso" }));

        lblSalario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblSalario.setText("Salário");

        txtFieldSalario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblFaltas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblFaltas.setText("Faltas");

        txtFieldFaltas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtFieldFaltas.setMinimumSize(new java.awt.Dimension(30, 22));

        checkBoxFuncionarioDoMes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        checkBoxFuncionarioDoMes.setText("Funcionário do mes");
        checkBoxFuncionarioDoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxFuncionarioDoMesActionPerformed(evt);
            }
        });

        lblAdmissao.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblAdmissao.setText("Admissão");

        btnFechar.setText("Fechar");

        btnSalvar.setText("Salvar");

        btnExcluir.setText("Excluir");

        btnEditar.setText("Editar");

        try {
            txtFormatedFieldAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatedFieldAdmissao.setToolTipText("");
        txtFormatedFieldAdmissao.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFaltas)
                            .addComponent(lblBonus)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxBonus, 0, 215, Short.MAX_VALUE)
                                    .addComponent(txtFieldNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdade)
                                    .addComponent(lblSalario))
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldFaltas, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxFuncionarioDoMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAdmissao)
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFieldSalario)
                            .addComponent(txtFieldIdade)
                            .addComponent(txtFormatedFieldAdmissao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(comboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBonus)
                            .addComponent(comboBoxBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdade)
                            .addComponent(txtFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSalario)
                            .addComponent(txtFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFaltas)
                                .addComponent(txtFieldFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkBoxFuncionarioDoMes)
                                .addComponent(lblAdmissao))
                            .addComponent(txtFormatedFieldAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxFuncionarioDoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFuncionarioDoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxFuncionarioDoMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox checkBoxFuncionarioDoMes;
    private javax.swing.JComboBox<String> comboBoxBonus;
    private javax.swing.JComboBox<String> comboBoxCargo;
    private javax.swing.JLabel lblAdmissao;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblFaltas;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JTextField txtFieldFaltas;
    private javax.swing.JTextField txtFieldIdade;
    private javax.swing.JTextField txtFieldNome;
    private javax.swing.JTextField txtFieldSalario;
    private javax.swing.JFormattedTextField txtFormatedFieldAdmissao;
    // End of variables declaration//GEN-END:variables
}
